spring.application.name=developExercise

mybatis.configuration.map-underscore-to-camel-case=true

<<<<<<< HEAD
mybatis.type-aliases-package=com.example.fullness.stationary.entity
=======
mybatis.type-aliases-package=ccom.example.fullness.stationary.entity
>>>>>>> 0cd2cfa305fefbe9e59555e49beccf0d58b5f14a

# Postgres接続情報を記入
spring.datasource.url=jdbc:postgresql://localhost:5432/development
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
