spring.application.name=developExercise

mybatis.configuration.map-underscore-to-camel-case=true

mybatis.type-aliases-package=ccom.example.fullness.stationary.entity

# Postgres接続情報を記入
spring.datasource.url=jdbc:postgresql://localhost:5432/development
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
