spring.application.name=demo

# ▼ PostgreSQL 接続設定（ユーザープロパティ）
spring.datasource.url=jdbc:postgresql://localhost:5432/development
spring.datasource.username=postgres
spring.datasource.password=postgres

# ▼ JPA（Hibernate）設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ▼ MyBatis 設定
mybatis.mapper-locations=classpath:com/example/fullness/stationary/repository/*.xml
mybatis.type-aliases-package=com.example.fullness.stationary.entity

# Disable Spring SQL initialization checks to avoid bean-definition detection issue during startup
spring.sql.init.enabled=false

server.servlet.session.timeout=30m
spring.mvc.throw-exception-if-no-handler-found=true

test.sql.clear=classpath:sql/clear.sql
test.sql.data=classpath:sql/data.sql


# ==========================================================================
# 定数の括管理定義 
# ==========================================================================
login.max-attempts=5
login.lock-minutes=1

product.max-price=1000000
product.max-stock=1000
product.allowed-image-extensions=jpg,jpeg,png
spring.application.name=demo
